micronaut:
  application:
    name: rewardMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://localhost:3307/rewards
    username: reward
    password: rewardsecret
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages:
        - com.loyalty.rewards.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  enabled: false