micronaut:
  application:
    name: userMicroservice
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/users
    username: user
    password: usersecret
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages:
        - com.loyalty.users.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
kafka:
  enabled: false
